from cad_order_gym.envs.cad_order_train_up import CADEnvTUP
from cad_order_gym.envs.cad_order_train_nup import CADEnvTNUP
from cad_order_gym.envs.cad_order_pred_up import CADEnvPUP
from cad_order_gym.envs.cad_order_pred_nup import CADEnvPNUP